controller:
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"


gateway:
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"
  proxy:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-name: kong
