controller:
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"


gateway:
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"