apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: np-arm64
  annotations:
    kubernetes.io/description: "NodePool for provisioning arm spot capacity"
spec:
  template:
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t4g.small"]
      nodeClassRef:
        name: default

  weight: 10
